language: node_js
node_js:
  - "6"
  - "5"
  - "4"

env:
  matrix:
    - WEBPACK_VERSION=1.13.1 EXTRACT_TEXT_VERSION=1
    - WEBPACK_VERSION=2.3.0 EXTRACT_TEXT_VERSION=2.1.0
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "4"
      env: WEBPACK_VERSION=2.3.0 EXTRACT_TEXT_VERSION=2.1.0
before_script:
  - npm rm webpack extract-text-webpack-plugin
  - npm install webpack@$WEBPACK_VERSION extract-text-webpack-plugin@$EXTRACT_TEXT_VERSION
cache:
  directories:
  - node_modules
